name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod download

    - name: Install gomocker
      run: go install github.com/jauhararifin/gomocker/gomocker

    - name: Go Generate
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go generate ./...

    - name: Test
      run: go test -v -race ./...
